### ISSUE TITLE
modal in front of a modal

### ISSUE THREAD

**Issue by siemya** [mmazzarolo/react-native-animated-modal#4]
Hey, 
In my app, i need to open a new modal in front of an existing modal, but i couldn't make it work...

**Comment by mmazzarolo** [comment]
Hey!  
Honestly... I never tried anything similar.   
I don't even know if it is possible using react-native own's modal component (which is the one I'm using in this library).  

Also, having more than one modal on screen is not really UX-friendly in my opinion (I can think of only 1 - 2 apps that implemented it nicely).  

Anyway, can you share the code you used?

**Comment by siemya** [comment]
Thanks for the fast response!
Actually my first modal is just a view i want to open via animation, the second one is an alert.
The alert doesn't need to animated, however it wont render in front of a modal when i give position absolute.

Basically my code:

<AnimatadView isVisible={isVisible}/>
<Alert  isVisible={isVisible}/>

Where both components are "react-native-animated-modal" inside.

**Comment by mmazzarolo** [comment]
Well, is seems correct to me... if it won't work I guess it's an "issue" with the react-native modal.  
I can't test it right now but you can have 2 options I guess:
1. Try to swap the `react-native-animated-modal` you used in the `Alert` with the react-native one (should be easy) and see if it works. If it doesn't work it must be a react-native issue.  
2. Use a `react-native` Alert instead of your custom one. I think it might have a "priority" over a modal.

**Comment by siemya** [comment]
I actually need to use my custom alert component.

Looks like it is an issue about react native Modal.

[]([https://github.com/facebook/react-native/issues/3445])

But sadly doesnt solve my problem, cause i can't use them in a nested way.

**Comment by mmazzarolo** [comment]
If you really need them the only way you can do something like that might be creating your own modal with `postition: absolute` and show it at the root level of you app when needed
